version: '3'

services:
#  rabbitmq_service:
#    image: "rabbitmq:3-management"
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - 'rabbitmq_data:/data'
#
#  nginx_api_gateway:
#    container_name: nginx_api_gateway
#    depends_on:
#      - user_service
#    build: ./nginx
#    networks:
#      - backend
#    volumes:
#      - "app_www:/usr/share/nginx/www"
#    ports:
#      - "3000:80"
#    expose:
#      - "80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/home/ruan/workspace/docker/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet

  kibana:
    image: 'docker.elastic.co/kibana/kibana:6.8.10'
    container_name: kibana
    environment:
      SERVER_NAME: kibana.local
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - esnet

  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - "9100:9100"
    networks:
      - esnet

networks:
#  backend:
#    driver: bridge
  esnet:

volumes:
  esdata1:
    driver: local
