version: '3'

services:
  user_service:
    build: ./user-service
    container_name: user_service
    volumes:
      - "./user-service:/src/app"
    hostname: user_service
    networks:
      - backend
    expose:
      - "3010"
    ports:
      - "3010:3010"
    depends_on:
      - user_service_db
      - rabbitmq_service
    working_dir: "/src/app"
    command: npm run start:dev

  rabbitmq_service:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

  nginx_api_gateway:
    container_name: nginx_api_gateway
    depends_on:
      - user_service
    build: ./nginx
    networks:
      - backend
    volumes:
      - "app_www:/usr/share/nginx/www"
    ports:
      - "3000:80"
    expose:
      - "80"

networks:
  backend:
    driver: bridge

volumes:
  app_www:
    external: true
  rabbitmq_data:
